modLoader = "javafml"
loaderVersion = "[46,)"
license = "${license}"
issueTrackerURL = "${issues}"

[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${modName}"
description = '''${modDescription}'''
authors = "${authors}"
displayURL = "${homepage}"
logoFile = "logo.png"

[[dependencies.${modId}]]
modId = "forge"
mandatory = true
versionRange = "[${forge},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "minecraft"
mandatory = true
versionRange = "[${mc}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "commonnetworking"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "moonlight"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "midnightlib"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.${modId}]]
modId = "dataanchor"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"