modLoader = "javafml"
loaderVersion = "[4,)"
license = "${license}"
issueTrackerURL = "${issues}"

[[mods]]
modId = "${modId}"
version = "${version}"
displayName = "${modName}"
description = '''${modDescription}'''
authors = "${authors}"
displayURL = "${homepage}"
logoFile = "assets/${modId}/icon.png"

[[mixins]]
config = "via_romana.mixins.json"

[[dependencies.${ modId }]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modId }]]
modId = "minecraft"
type = "required"
versionRange = "[${mc},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modId }]]
modId = "fabric_api"
type = "required"
versionRange = "[${forgeFapi},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ modId }]]
modId = "midnightlib"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"